# Generated by Django 5.2 on 2025-04-20 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmoney_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=255)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmoney_tracker.budget')),
            ],
        ),
    ]
